### PR TITLE
Fixed sleep: added HKCategoryTypeIdentifier, timeZone and sleepStatus

### LINKED ISSUE #3: Sleep data returns: {"errorDescription": "sampleTypeFailed"}
Hey! Thanks so much for making this, it's super cool!

I've run into a problem when trying to to get Sleep data from HealthKit. Instead of getting sleep data back I get this:

{
    "errorDescription": "sampleTypeFailed"
}

I don't have much experience with Swift/iOS development, otherwise I'd make a PR request instead!

If there's anything I'm doing wrong as well, please let me know, I'm querying with the sample name: "sleepAnalysis", and as far as I understand, sleep falls under the "activity" Authorisation permission? Maybe Apple has changed this?

### PR DESCRIPTION
**Pull request by michaeljelly**
As I mentioned in https://github.com/Ad-Scientiam/capacitor-healthkit/issues/3 it seemed like sleepAnalysis wasn't working for me. I'm not 100% sure, but having looked at the code it seemed like .sleepAnalysis was the only sampleType that didn't have its TypeIdentifier as the object it was referencing.

Hopefully this fixes that, so that sleep data can be queried.

Closes #3

### CODE REVIEW

**Comment by michaeljelly** [comment]
New update: this didn't fix it, but I have a new theory.

I think it's this line, because I think what comes back from sleepAnalysis is a HKCategorySample rather than a HKQuantitySample: https://github.com/Ad-Scientiam/capacitor-healthkit/blob/c39a2f1aa424c18c8a672a87772f85f7ecc24027/ios/Plugin/Plugin.swift#L319

So that line returns nil, which then triggers the error in this line: https://github.com/Ad-Scientiam/capacitor-healthkit/blob/c39a2f1aa424c18c8a672a87772f85f7ecc24027/ios/Plugin/Plugin.swift#L545

Will test and report back.

**Comment by arnauddrain** [comment]
Hello, thank you for your investment!
Could you suggest a protocol to test this?

**Comment by michaeljelly** [comment]
No problem! What do you mean by a protocol to test this?

Making it into an HKCategorySample does seem to get things working which is good! I'm just making a few other improvements like adding a "sleepState": of "InBed" or "Asleep", and will also add the timezone of the sleeping, as that helps you to ensure localised accuracy as to what their wake-up and sleep times are.

**Comment by michaeljelly** [comment]
Ok @arnauddrain it's all working for me now! I've also added TimeZone and sleepStatus (i.e. "Asleep" or "InBed") to make it easier to use the output.

Instead of `sampleTypeFailed` I now get this:

`"sleepAnalysis": ["countReturn": 3, "resultData": [["uuid": "296F61C6-7A59-4722-AAB8-22F6198B20BE", "source": "Sleep Cycle", "endDate": "2021-07-21T08:30:37Z", "sourceBundleId": "com.lexwarelabs.goodmorning", "duration": 8.481006005273924, "timeZone": "+01:00", "sleepState": "InBed", "startDate": "2021-07-21T00:01:46Z"], ["endDate": "2021-07-21T08:00:00Z", "sleepState": "InBed", "uuid": "D8C7710C-1699-4D13-990B-73D98A99514B", "startDate": "2021-07-21T00:01:48Z", "sourceBundleId": "com.apple.health.56F3EAB3-86CB-4683-9D6B-704B32DA3085", "duration": 7.9701501669486365, "source": "Michael’s iPhone", "timeZone": "+01:00"], ["endDate": "2021-07-21T06:57:20Z", "duration": 6.75653478420443, "startDate": "2021-07-21T00:11:56Z", "timeZone": "+01:00", "sourceBundleId": "com.lexwarelabs.goodmorning", "sleepState": "Asleep", "uuid": "7A0917A5-6523-4116-9102-17597F56E859", "source": "Sleep Cycle"]]],`

Let me know if there's anything else you want done, or what you mean by a protocol to test this. Will remove draft tag as it's ready to be merged from my perspective.

**Comment by michaeljelly** [comment]
closes #3

**Comment by arnauddrain** [comment]
Thank you again @michaeljelly! 🙏 
By "a protocol to test this" I was asking for a sample of code that I could run to validate that the code is working. But everything seems fine, I will publish a new version right now

**Comment by arnauddrain** [comment]
[Released in v0.1.7](https://www.npmjs.com/package/capacitor-healthkit)

**Pull request merged**
