### PR TITLE
Support more SampleTypes

### PR DESCRIPTION
**Pull request by T-Ralph**
restingHeartRate, respiratoryRate, bodyFat, oxygenSaturation, basalBodyTemperature, bodyTemperature, bloodPressureSystolic, and bloodPressureDiastolic.

@mahnuh Please, take a look at this.
Thank you.

### CODE REVIEW

**Comment by dheerajkumarsqm** [comment]
In my repository, I have added code for restingHeartRate, respiratoryRate, and bodyTemperature. I hope this helps. 
https://github.com/dheerajkumarsqm/capacitor-healthkit/blob/main/ios/Plugin/CapacitorHealthkitPlugin.swift

**Comment by T-Ralph** [comment]
Hello @mahnuh 
If you have some time, kindly, take a look at this.
Thank you.

**Comment by T-Ralph** [comment]
@mahnuh  Please, check this out whenever you can :-)

**Comment by dancornell** [comment]
This would also be super-helpful for me :)

I'd actually be happy to help flesh out some additional SampleTypes if PRs would be welcome.

**Comment by T-Ralph** [comment]
@mahnuh  @crcht  @arnauddrain  @fynnlyte  @alemf 
A gentle reminder to review this PR whenever you can :-)
Thank you.

**Comment by olx-xlo** [comment]
Thank you for your work!

**Comment by mahnuh** [comment]
@T-Ralph please be aware that the main branch is kinda deprecated and that we are only working on the v2 branch, which is a total re-write from the ground up. main will be replaced in the future, no timeline yet. But form now on we will no longer accept PRs on main.

**Comment by T-Ralph** [comment]
Thank you @mahnuh for merging the PR and for the additional clarification.

**Pull request merged**
